version: '3'
services:
  db:
    image: postgres:16.0
    container_name: db
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
      - ./custom_postgresql.conf:/etc/postgresql/postgresql.conf
      - ./benchmark.sql:/benchmark.sql
    ports:
      - 5433:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '1'
          memory: 500M
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram
